import { library } from '@fortawesome/fontawesome-svg-core'
import { 
  faPlayCircle,
  faEnvelope,
  faHome,
  faUser,
  faGuitar,
  /* faPiano, */
  faSlidersH,
  faMicrophone,
  faMusic,
  faLayerGroup,
  faGraduationCap,
  faAward,
  faChalkboardUser,
  faTheaterMasks,
  faMapPin,
  faPhone,
  faCar,
  faLaptop,
  faGift,
  faArrowUp,
  faChevronDown,
  faArrowDown,
  faMapMarkerAlt,
  faUserGraduate,
  faUserCircle,
  faList,
  faBullseye,
  faTools,
  /* faTarget, */
  faChartLine,
  faTrophy,
  faStar,
  /* faCable, */
  faPlay,
  faClock,
  faMobileAlt,
  faHourglassHalf,
  faEye,
  faHandPaper,
  faVolumeUp,
  faHandRock,
  faUsers,
  faPalette,
  faPen,
  /* faEqualizer, */
  faHeadphones,
  faCog
} from '@fortawesome/free-solid-svg-icons'

// Add all icons to the library
library.add(
  faPlayCircle,
  faEnvelope,
  faHome,
  faUser,
  faGuitar,
  /* faPiano, */
  faSlidersH,
  faMicrophone,
  faMusic,
  faLayerGroup,
  faGraduationCap,
  faAward,
  faChalkboardUser,
  faTheaterMasks,
  faMapPin,
  faPhone,
  faCar,
  faLaptop,
  faGift,
  faArrowUp,
  faChevronDown,
  faArrowDown,
  faMapMarkerAlt,
  faUserGraduate,
  faUserCircle,
  faList,
  faBullseye,
  faTools,
  /* faTarget, */
  faChartLine,
  faTrophy,
  faStar,
  /* faCable, */
  faPlay,
  faClock,
  faMobileAlt,
  faHourglassHalf,
  faEye,
  faHandPaper,
  faVolumeUp,
  faHandRock,
  faUsers,
  faPalette,
  faPen,
  /* faEqualizer, */
  faHeadphones,
  faCog
)
